@startuml class diagram

title: クラス図

left to right direction

'クラスの宣言
package "V" {

  'GoogleMapを表示する
  class MapView {
  }

  '検索地リストを表示する
  class PlaceListView {
  }
}


package "VM" {

  '検索機能を提供する
  class SearchArea {
    +searchPlace: String
    +doSearch()
  }

  class MapViewModel {
    +nowPlace: Place
    +nowWeather: WeatherInfo
  } 
  
  class PlaceListViewModel {
    +placeList
  }
}
note bottom: ViewModeクラスはviewModeを継承する

package "M" {
  class Repositry {
    +getWeaherInfo()
    +getPlaceList()
    +addPlace()
  }

  class Weather <<retrofit>> {
    +getWeatherInfo()
  }

  class DBPlace <<Room>> {
    +getPlaceList()
    +addPlace
  }
}

package Utility {

  '場所を表すデータクラス
  class Place <<data class>> {
    +placeName: String //場所名
    +longitude: Double //緯度
    +latitude: Double //経度
  }

  '天気情報を表すデータクラス
  class WeatherInfo <<data class>> {
    +weatherID: String //天気ID
    +iconPath: String //天気アイコンのパス
  }

  '地理情報変換
  class Geo {
    +getGeoInfo() //文字列から緯度経度を取得する
  }
}

'クラス関連
' MapViewはGooglemapを保持
OnMapReadyCallback ()-- MapView

MapView --> MapViewModel : Data Bind / observer
PlaceListView --> PlaceListViewModel : observer

' VMクラスはviewModelを継承
MapViewModel <--> Repositry : observer
PlaceListViewModel <--> Repositry : observer

' DBとWebAPIアクセスはクラスに任せる
Repositry <--> Weather
Repositry <--> DBPlace

' VMは検索インターフェースを使う
MapViewModel -|> SearchArea
PlaceListViewModel -|> SearchArea

@enduml