@startuml class diagram

title: クラス図

'クラスの宣言
package "V" {

  'GoogleMapを表示する
  class MapActivity #00FF00 {
    +mSearchText: EditText

    -weatherObserve() //天気情報が更新されたらMapに反映
    -searchLatLngObserve() //位置情報が更新されたらMapに反映
  }

  class WeatherMarker{
    -Marker? //マーカー位置はひとつだけ

    +getInstance() //Singlton

    +addWeatherMarker()
    +addMarker()
    -removeWeatherMarker()
    -getIconID()
  }
}

package "VM" {

  class MapsViewModel #00FF00  {
    searchPlaceString: String //検索文字列をBinding
    weatherStatus //天気情報 LiveData
    searchLatLng //位置情報 LiveData

    setMapClickPos() //weatherStatusを更新
  } 

}

package "M" {
  class Repositry #00FF00  {
    +getWeather()
    +getPlaceDBData()
    +insertDBPlaceData()
  }

  class OpenWeatherMapAccess{
    +getWeatherInfobyLatLng()
  }

  class PlaceDBAccess {
    +getPlaceDBData()
    +insertDBPlaceData()
  }

  class PlaceDatabase{
  }

  interface PlaceDBDAO{
    +insert()
    +getAll()
    +eleteAll()
  }
}

package data {

  '場所を表すデータクラス
  class PlaceDBData <<data class>> {
    +placeName: String //場所名
    +longitude: Double //緯度
    +latitude: Double //経度
  }

  '天気情報を表すデータクラス
  class WeatherData <<data class>> {
    +weatherID: String //天気ID
    +iconPath: String //天気アイコンのパス
  }

}

'クラス関連
' MapActivityはGooglemapを保持
WeatherMarker -> MapActivity : Singleton

MapActivity -> MapsViewModel : DataBinding / LiveData(Observe)

' VMクラスとMクラス
MapsViewModel -> Repositry

' DBとWebAPIアクセスはクラスに任せる
Repositry --> OpenWeatherMapAccess
Repositry --> PlaceDBAccess

PlaceDBAccess --> PlaceDatabase
PlaceDBAccess --> PlaceDBDAO

WeatherMarker -[hidden]do- WeatherData

@enduml