@startuml dispWeatherInfo

title: タップからの情報表示

Actor "User" as USER
participant MapsView order 10 #00FF00
participant WeatherMarker order 20
participant MapsViewModel order 30 #00FF00
participant Repositry order 40 #00FF00
participant OpenWeatherMapAccess order 50

skinparam SequenceMessageAlignment center

USER -> MapsView : 地図タップを検知
MapsView -> MapsViewModel : 位置情報
group コルーチン（別スレッド）
MapsViewModel -> Repositry : get(位置情報)
Repositry -> OpenWeatherMapAccess : get(位置情報)
OpenWeatherMapAccess -> Repositry : 天気情報
Repositry -> MapsViewModel : 天気情報
MapsViewModel -> MapsViewModel : 天気情報更新
end
MapsViewModel --> MapsView : Observe
MapsView -> WeatherMarker : get
WeatherMarker -> MapsView : iconデータ
MapsView -> MapsView : Map更新

@enduml

@startuml linsertWeatherInfo

title: 天気位置情報のDB登録

Actor "User" as USER
participant MapsView order 10 #00FF00
participant MapsViewModel order 30 #00FF00
participant Repositry order 40 #00FF00
participant PlaceDBAccess order 50
participant PlaceDBDAO order 60

skinparam SequenceMessageAlignment center

USER -> MapsView : 位置設定
group コルーチン（別スレッド）
MapsView -> MapsViewModel : insert
MapsViewModel -> Repositry : insert
Repositry -> PlaceDBAccess : insert
PlaceDBAccess -> PlaceDBDAO : insert
end

@enduml